### ISSUE TITLE
Add Pop-ups For publishModrinth Task

### ISSUE THREAD

**Issue by sylv256** [VulpixelMC/libreg#9]
Show pop-ups for the modrinth changelog and version name when running the `publishModrinth` task.

**Comment by sylv256** [comment]
swing would work good with this

**Comment by sylv256** [comment]
javafx maybe

**Comment by ENDERZOMBI102** [comment]
wdym by “popup”?
also idk how to kotlin

**Comment by sylv256** [comment]
> wdym by “popup”?
> also idk how to kotlin

thing that pops up on screen where you type other thing
https://kotlinlang.org/

**Comment by TehcJS** [comment]
> swift would work good with this

swing not swift. swift is cursed

**Comment by sylv256** [comment]
No longer necessary.
